server:
  port : 9090
  
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: jwigumeongteam@gmail.com
    password: aiqylfssvoehcxvd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
         
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
    
logging:
  level:
    '[org.hibernate.SQL]': debug
    

file:
  upload-dir: uploads/resources/fileupload/
  